version: 2.0.{build}
configuration: Release
cache: source\packages -> **\packages.config
build:
  project: source\DotSpatial.sln
  verbosity: minimal
artifacts:
- path: source\bin\Release
  name: Release
